### PR TITLE
Enhanced readme of org profile

### PR DESCRIPTION
**Pull request by NS007-dev**
@1upcommunity I tried to enhance the profile readme. Thank you.

### CODE REVIEW

**Comment by N3RDIUM** [comment]
Thanks!

**Comment by N3RDIUM** [comment]
I've sent you a join request.

**Comment by NS007-dev** [comment]
Thank you @somePythonProgrammer

**Comment by N3RDIUM** [comment]
Your avatar will be added to the [website](https://1upCommunity.github.io) next week.

**Pull request merged**
